version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
        environment:
          WOW_ADDON_DIR: "/home/circleci/wow/_retail_/Interface/AddOns/"
    steps:
      - checkout
      - run: mkdir -p "$WOW_ADDON_DIR"
      - run: ./wow-addons
      - run: ls $WOW_ADDON_DIR
      
      - store_artifacts:
          path: /home/circleci/wow/_retail_/Interface/AddOns/
          destination: addons.zip
